spring.application.name=Hannime

# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:hannime.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=

# MyBatis-Plus Configuration
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
mybatis-plus.global-config.db-config.id-type=input
mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml

# Logging Configuration
logging.config=classpath:logback-spring.xml
logging.level.com.shikou.hannime=DEBUG

hannime.zone=HK
hannime.lang=zhs

video.store.path=C:/Users/Admin/Downloads/
video.min.code=10
video.max.code=20
video.resolution=360p